version: 2
jobs:
  build:
    docker:
      - image: tablet02/hw02
    steps:
      - checkout
      - run: ls  
workflows:
  version: 2
  commit:
    jobs:
      - build

  nightly:
    triggers:
      - schedule:
          cron: "0 0,5,10,15,20 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
